targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: lib/src/api
          output_folder: lib/src/api/generated
          include_if_null: false