name: ioka
description: Flutter SDK for ioka
version: 0.0.1
homepage: https://ioka.kz
repository: https://github.com/iokadev/ioka-flutter
issue_tracker: https://github.com/iokadev/ioka-flutter/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  chopper: ^4.0.1
  credit_card_type_detector: ^2.0.0
  credit_card_validator: ^2.0.1
  flutter_keyboard_visibility: ^5.2.0
  flutter_svg: ^1.0.3
  functional_listener: ^2.1.0
  json_annotation: ^4.4.0
  provider: ^6.0.2
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  chopper_generator: ^4.0.2
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.1

flutter:
  assets:
    - lib/assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400

        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600