name: ioka
description: Flutter SDK for ioka.kz
version: 1.0.1
homepage: https://ioka.kz
repository: https://github.com/iokadev/ioka-flutter
issue_tracker: https://github.com/iokadev/ioka-flutter/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  chopper: ^4.0.1
  collection: ^1.15.0
  credit_card_type_detector: ^2.0.0
  credit_card_validator: ^2.0.1
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  provider: ^6.0.2
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  alchemist: ^0.2.1
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  chopper_generator: ^4.0.2
  json_serializable: ^6.1.4
  mockito: ^5.1.0
  meta: ^1.7.0
  swagger_dart_code_generator: ^2.4.1

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/icons/
    - lib/assets/icons/card_types/
    - lib/assets/icons/card_emitters/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400

        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600