name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse fvm config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      
      - name: Install packages
        run: flutter pub get
      
      - name: Install packages in ./demo
        run: cd demo && flutter pub get
      
      - name: Generate coverage helper test
        run: ./tool/generate_coverage_helper.sh

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Remove generated files from coverage
        run: ./tool/remove_generated_files_from_coverage.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true
